ALTER TABLE players ADD COLUMN magic INTEGER NOT NULL DEFAULT 1;
ALTER TABLE players ADD COLUMN stamina INTEGER NOT NULL DEFAULT 100;
ALTER TABLE players ADD COLUMN max_stamina INTEGER NOT NULL DEFAULT 100;
ALTER TABLE players ADD COLUMN status_effects TEXT NOT NULL DEFAULT '[]';
ALTER TABLE players ADD COLUMN combat_abilities TEXT NOT NULL DEFAULT '[]';
