services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_PATH=/data/game.db
      - GIN_MODE=release
    volumes:
      - game-data:/data
    depends_on:
      - migrations

  migrations:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["./server", "-migrate"]
    environment:
      - DB_PATH=/data/game.db
    volumes:
      - game-data:/data
    restart: on-failure

volumes:
  game-data:
