name: Go Lint and Format

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest

      - name: Run golangci-lint
        working-directory: ./backend
        run: golangci-lint run

      - name: Check gofumpt formatting
        working-directory: ./backend
        run: |
          gofumpt -l .
          test -z $(gofumpt -l .)

      - name: Check go fmt
        working-directory: ./backend
        run: |
          go fmt ./...
          test -z $(git status --porcelain)
